name: Test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_OUT_ROOT: ${{ github.workspace }}/mdn/content/node_modules/@mdn/fred/out

    steps:
      - name: Checkout mdn/content
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: mdn/content
          path: mdn/content
          persist-credentials: false

      - name: Checkout mdn/curriculum
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          path: mdn/curriculum
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: mdn/content/.nvmrc
          cache: npm
          cache-dependency-path: mdn/content/package-lock.json

      - name: Install
        run: npm ci
        working-directory: mdn/content

      - name: Build
        working-directory: mdn/content
        env:
          CONTENT_ROOT: ${{ github.workspace }}/mdn/content/files
          CURRICULUM_ROOT: ${{ github.workspace }}/mdn/curriculum
          GITHUB_TOKEN: ${{ github.token }}
        run: npx rari build --no-basic --curriculum --issues "$BUILD_OUT_ROOT/issues.json" --templ-stats

      - name: Report
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        env:
          FILES_PATH: ${{ github.workspace }}/mdn/curriculum
          ISSUES_PATH: ${{ env.BUILD_OUT_ROOT }}/issues.json
        with:
          script: |
            const fs = require("fs");

            const issuesByPath = JSON.parse(fs.readFileSync(process.env.ISSUES_PATH, "utf8"));

            for (const [filepath, issues] of Object.entries(issuesByPath)) {
              const prefix = process.env.FILES_PATH.replace(/\/?$/, "/");

              if (!filepath.includes(prefix)) {
                continue;
              }

              const file = filepath.replace(prefix, "");
              const messages = [];

              for (const issue of issues) {
                const {
                  source = "unknown",
                  ...otherFields
                } = Object.fromEntries(issue.fields);

                const payload = Object.entries(otherFields)
                  .map(([key, value]) => `\x1b[38;2;37;136;235m${key}\x1b[0m: \x1b[38;2;221;0;169m${value}\x1b[0m`)
                  .join(" â€¢ ");

                const message = source ? `\x1b[3m(${source})\x1b[0m ${payload}` : payload;
                messages.push(message);
              }

              const message = `Found \x1b[1m${issues.length}\x1b[0m issue(s) in \x1b[1m${file}\x1b[0m:\n${messages.map(m => `${m}`).join("\n")}`;
              core.warning(message, { file });
            }
